name: ShowYourAuto
favicon: null
layout_spectrum: 0.24883
typography_spectrum: 0.83501
title: 'Show Your Auto LLC | Find What Drives You.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff5800'
    - '#d84b00'
    - '#963300'
    - '#b63f00'
    - '#5c2000'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
